service: cwl2slack
provider:
  name: aws
  region: ap-northeast-1
  stage:
  memorySize: 128
  runtime: python3.7
  versionFunctions: false
  tags:
    projecjt: ${self:custom.conf.base.project}
    env: ${opt:stage}
    role: ${self:service}
    created_by: ServerlessFramework
  environment:
    slack_url: ${self:custom.conf.${opt:stage}.slack_url}
    slack_channel: ${self:custom.conf.${opt:stage}.slack_channel}
    re_exclude_word: ${self:custom.conf.${opt:stage}.re_exclude_word}

custom:
  conf:
    base: ${file(./conf/base.yml)}
    common: ${file(./conf/common.yml)}
    prod: ${file(./conf/prod.yml)}
    stg: ${file(./conf/stg.yml)}

functions:
  cwl2slack:
    name: ${self:custom.conf.base.project}-${opt:stage}-${self:service}-lambda
    handler: main.lambda_handler
    description: Managed by ServerlessFramework
